//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientBook.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int Id { get; set; }
        public byte[] Name { get; set; }
        public byte[] Address_ { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    }
}
